export const DateFormatter = {
    MONTHS: ['Jan', 'Feb', 'March', 'April', 'May', 'June', 'July', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec'],
    LONG_MONTHS: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    DAYS: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    daysInYear: (y = null) => { const year = y ?? new Date().getFullYear(); return (year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0)) ? 366 : 365; },
};

export const fireIcons = ['', 'out', 'big', 'controlled', 'contained', 'large', 'large-inactive', 'complex', 'new', 'new-big', 'rx', 'smoke'];

export const stateLabels = {
    'AB': { name: 'Alberta', center: [-113.5, 54.5] },
    'ACT': { name: 'Australian Capital Territory', center: [149.0014, -35.4900] },
    'AL': { name: 'Alabama', center: [-86.8295337, 33.2588817] },
    'AK': { name: 'Alaska', center: [-149.680909, 64.4459613] },
    'AZ': { name: 'Arizona', center: [-111.7632755, 34.395342] },
    'AR': { name: 'Arkansas', center: [-92.4479108, 35.2048883] },
    'BC': { name: 'British Columbia', center: [-123.5, 54.5] },
    'CA': { name: 'California', center: [-118.7559974, 36.7014631] },
    'CO': { name: 'Colorado', center: [-105.6077167, 38.7251776] },
    'CT': { name: 'Connecticut', center: [-72.7342163, 41.6500201] },
    'DE': { name: 'Delaware', center: [-75.4013315, 38.6920451] },
    'DC': { name: 'District of Columbia', center: [-77.0365529, 38.8948932] },
    'FL': { name: 'Florida', center: [-81.4639835, 27.7567667] },
    'GA': { name: 'Georgia', center: [-83.1137366, 32.3293809] },
    'HI': { name: 'Hawaii', center: [-157.975203, 21.2160437] },
    'ID': { name: 'Idaho', center: [-114.74121, 45.61788] },
    'IL': { name: 'Illinois', center: [-89.4337288, 40.0796606] },
    'IN': { name: 'Indiana', center: [-86.1746933, 40.3270127] },
    'IA': { name: 'Iowa', center: [-93.3122705, 41.9216734] },
    'KS': { name: 'Kansas', center: [-98.5821872, 38.27312] },
    'KY': { name: 'Kentucky', center: [-85.1551411, 37.5726028] },
    'LA': { name: 'Louisiana', center: [-92.007126, 30.8703881] },
    'MB': { name: 'Manitoba', center: [-97.8, 55.0] },
    'ME': { name: 'Maine', center: [-68.8590201, 45.709097] },
    'MD': { name: 'Maryland', center: [-76.9382069, 39.5162234] },
    'MA': { name: 'Massachusetts', center: [-72.032366, 42.3788774] },
    'MI': { name: 'Michigan', center: [-84.6824346, 43.6211955] },
    'MN': { name: 'Minnesota', center: [-94.6113288, 45.9896587] },
    'MS': { name: 'Mississippi', center: [-89.7348497, 32.9715645] },
    'MO': { name: 'Missouri', center: [-92.5617875, 38.7604815] },
    'MT': { name: 'Montana', center: [-109.6387579, 47.3752671] },
    'NB': { name: 'New Brunswick', center: [-66.0, 46.5] },
    'NE': { name: 'Nebraska', center: [-99.5873816, 41.7370229] },
    'NL': { name: 'Newfoundland', center: [-58.0, 53.0] },
    'NS': { name: 'Nova Scotia', center: [-63.5, 45.0] },
    'NSW': { name: 'New South Wales', center: [147.0167, -32.1633] },
    'NV': { name: 'Nevada', center: [-116.8537227, 39.5158825] },
    'NH': { name: 'New Hampshire', center: [-71.6553992, 43.4849133] },
    'NJ': { name: 'New Jersey', center: [-74.4041622, 40.0757384] },
    'NM': { name: 'New Mexico', center: [-105.993007, 34.5708167] },
    'NY': { name: 'New York', center: [-74.0060152, 40.7127281] },
    'NC': { name: 'North Carolina', center: [-79.0392919, 35.6729639] },
    'ND': { name: 'North Dakota', center: [-100.540737, 47.6201461] },
    'NT': { name: 'Northwest Territories', center: [-117.0, 64.0] },
    'NTT': { name: 'Northern Territory', center: [133.3578, -19.3833] },
    'NU': { name: 'Nunavut', center: [-90.0, 71.0] },
    'OH': { name: 'Ohio', center: [-82.6881395, 40.2253569] },
    'OK': { name: 'Oklahoma', center: [-97.2684063, 34.9550817] },
    'ON': { name: 'Ontario', center: [-84.0, 50.0] },
    'OR': { name: 'Oregon', center: [-120.737257, 43.9792797] },
    'PA': { name: 'Pennsylvania', center: [-77.7278831, 40.9699889] },
    'PE': { name: 'Prince Edward Island', center: [-63.5, 46.3] },
    'QC': { name: 'Quebec', center: [-71.5, 52.0] },
    'QLD': { name: 'Queensland', center: [144.4317, -22.4870] },
    'RI': { name: 'Rhode Island', center: [-71.5992372, 41.7962409] },
    'SA': { name: 'South Australia', center: [135.7633, -30.0583] },
    'SC': { name: 'South Carolina', center: [-80.4363743, 33.6874388] },
    'SD': { name: 'South Dakota', center: [-100.348761, 44.6471761] },
    'SK': { name: 'Saskatchewan', center: [-106.0, 52.0] },
    'TAS': { name: 'Tasmania', center: [146.5933, -42.0214] },
    'TN': { name: 'Tennessee', center: [-86.2820081, 35.7730076] },
    'TX': { name: 'Texas', center: [-99.5120986, 31.8160381] },
    'UT': { name: 'Utah', center: [-111.7143584, 39.4225192] },
    'VIC': { name: 'Victoria', center: [144.2800, -36.8542] },
    'VT': { name: 'Vermont', center: [-72.5002608, 44.5990718] },
    'VA': { name: 'Virginia', center: [-78.4927721, 37.1232245] },
    'WA': { name: 'Washington', center: [-120.74014, 47.75107] },
    'WAA': { name: 'Western Australia', center: [122.2983, -25.3281] },
    'WV': { name: 'West Virginia', center: [-80.8408415, 38.4758406] },
    'WI': { name: 'Wisconsin', center: [-89.6884637, 44.4308975] },
    'WY': { name: 'Wyoming', center: [-107.5685348, 43.1700264] },
    'YT': { name: 'Yukon', center: [-135.0, 62.0] }
};

export const legend = {
    'categories': [
        { 'fire': 'Wildfires' },
        { 'viirs': 'VIIRS Hotspots' },
        { 'airQ': 'Air Quality' },
        { 'smoke': 'Smoke Forecast' },
        { 'drought': 'Drought Conditions' },
        //{ 'nfdrs': 'Fire Danger' },
        { 'sfp': 'Significant Fire Potential' },
        { 'erc': 'Energy Release Component' },
        /*{ 'burnProb': 'Burn Probability' },*/
        { 'fhsz': 'CAL FIRE Hazard Severity Zones' },
        { 'lands': 'Land Ownership' },
        { 'spc': 'SPC Fire Climatology' },
        { 'rth': 'Wildfire Risk to Homes' },
        { 'wet': 'Wildfire Exposure Type' },
        { 'bp': 'Wildfire Likelihood' },
        { 'whp': 'Wildfire Hazard Potential' },
        { 'nri': 'FEMA Wildfire Risk Index' }
    ],
    'items': {
        'fire': [
            ['img', 'new', '', 'New Fire', 16],
            ['img', 'new-big', '', 'Fast Growing, New Fire', 24],
            ['img', 'big', '', 'Active Fire (0-100 acres)', 16],
            ['img', '', '', 'Active Fire (100-1000 acres)', 16],
            ['img', 'large', '', 'Active Fire (>1000 acres)', 24],
            ['img', 'complex', '', 'Fire Complex', 28],
            ['img', 'contained', '', 'Contained Fire', 14],
            ['img', 'controlled', '', 'Controlled Fire', 14],
            ['img', 'rx', '', 'Prescribed Burn', 24],
            ['img', 'smoke', '', 'Smoke Check', 16]
        ],
        'airQ': [
            ['color', '', '#00e400', 'Good (0-50)'],
            ['color', '', '#ffff00', 'Moderate (51-100)'],
            ['color', '', '#ff7e00', 'Unhealthy for Sensitive Groups (101-150)'],
            ['color', '', '#ff0000', 'Unhealthy (151-200)'],
            ['color', '', '#8f3f97', 'Very Unhealthy (201-300)'],
            ['color', '', '#7e0023', 'Hazardous (301+)'],
            ['color', '', '#d9d9d9', 'No Data'],
        ],
        'viirs': [
            ['icon', '<div class="viirs t24"></div>', '', 'Heat Detection (0-24 hours old)'],
            ['icon', '<div class="viirs t48"></div>', '', 'Heat Detection (24-48 hours old)'],
            ['icon', '<div class="viirs t72"></div>', '', 'Heat Detection (48-72 hours old)']
        ],
        'smoke': [
            ['color', '', '#ffffc0', 'Very Clean (0-3 µg/m³)'],
            ['color', '', '#fcdf8b', 'Light Smoke (3-25 µg/m³)'],
            ['color', '', '#f6c26d', 'Moderate Smoke (25-63 µg/m³)'],
            ['color', '', '#c5885c', 'Heavy Smoke (63-158 µg/m³)'],
            ['color', '', '#974f4f', 'Very Heavy Smoke (158-1000 µg/m³)'],
            ['color', '', '#f8fed0', 'No Data']
        ],
        /*'nfdrs': [
            ['color', '', '#3db471', 'Low'],
            ['color', '', '#00ff00', 'Moderate'],
            ['color', '', '#ffff00', 'High'],
            ['color', '', '#ff8b00', 'Very High'],
            ['color', '', '#b31f1f', 'Extreme']
        ],*/
        'sfp': [
            ['color', '', '#85ca0a', 'Little or No Risk'],
            ['color', '', '#ffff00', 'Low Risk'],
            ['color', '', '#ad7c23', 'Moderate Risk'],
            ['color', 'D', '#ff9900', 'Dry'],
            ['color', 'W', '#ff9900', 'Hot & Dry'],
            ['color', 'H', '#ff9900', 'Hot'],
            ['color', 'U', '#ff9900', 'Unstable'],
            ['color', 'L', '#ff0000', 'Lightning'],
            ['color', 'R', '#ff0000', 'Recreation'],
            ['color', 'B', '#ff0000', 'Burn Environment']
        ],
        'spc': [
            ['color', '', '#fff', '2-5%'],
            ['color', '', '#ffdfbf', '5-10%'],
            ['color', '', '#ffab57', '10-15%'],
            ['color', '', '#ff7500', '15-20%'],
            ['color', '', '#ee3f00', '20-25%'],
            ['color', '', '#c80b00', '25-30%'],
            ['color', '', '#9f0000', '30-35%'],
            ['color', '', '#760000', '35-40%'],
            ['color', '', '#500000', '40-45%'],
            ['color', '', '#270000', '45-50%']
        ],
        'erc': [
            ['color', '', '#38a800', '<60% higher than normal'],
            ['color', '', '#d1ff73', '60-79.9% higher than normal'],
            ['color', '', '#ffffbe', '80-89.9% higher than normal'],
            ['color', '', '#ffaa00', '90-96.9% higher than normal'],
            ['color', '', '#ff0000', '97-99.9% higher than normal'],
            ['color', '', '#a80000', '>=100% higher than normal'],
            ['color', '', '#e1e1e1', 'No data'],
        ],
        /*'burnProb': [
            ['color', '', '#fff0cf', '0-0.01%'],
            ['color', '', '#fddcaf', '0.01-0.02%'],
            ['color', '', '#fdca94', '0.02-0.05%'],
            ['color', '', '#fdb27b', '0.05-0.1%'],
            ['color', '', '#fc8d59', '0.1-0.2%'],
            ['color', '', '#f26d4b', '0.2-.05%'],
            ['color', '', '#e1452f', '0.5-1%'],
            ['color', '', '#c91d13', '1-2.2%'],
            ['color', '', '#a90000', '2.2-4.5%'],
            ['color', '', '#7f0000', '4.5-12.5%']
        ],*/
        'fhsz': [
            ['color', '', '#ffff69', 'Moderate'],
            ['color', '', '#ffcd69', 'High'],
            ['color', '', '#ff6969', 'Very High']
        ],
        'nri': [
            ['color', '', '#4d6dbd', 'Very Low'],
            ['color', '', '#509bc7', 'Relatively Low'],
            ['color', '', '#f0d55d', 'Relatively Moderate'],
            ['color', '', '#e07069', 'Relatively High'],
            ['color', '', '#c7445d', 'Very High'],
            ['color', '', '#ffffff', 'No Rating'],
            ['color', '', '#9e9e9e', 'Insufficient Data']
        ],
        'lands': [
            ['color', '', '#fcb5ce', 'Department of Defense'],
            ['color', '', '#fee67a', 'Bureau of Land Management'],
            ['color', '', '#cabddd', 'National Park Service'],
            ['color', '', '#cdecc5', 'U.S. Forest Service'],
            ['color', '', '#7fcda7', 'U.S. Fish & Wildlife Service'],
            ['color', '', '#ffffb4', 'Bureau of Reclamation'],
            ['color', '', '#fdb56b', 'Bureau of Indian Affairs'],
            ['color', '', '#e4c4a0', 'Other Federal'],
            ['color', '', '#b4e3ef', 'State']
        ],
        'rth': [
            ['color', '', '#ffffff', '0 percentile'],
            ['color', '', '#f1f2a0', '0-40th percentile'],
            ['color', '', '#f2c13c', '40-70th percentile'],
            ['color', '', '#f28017', '70-90th percentile'],
            ['color', '', '#f21900', '90-95th percentile'],
            ['color', '', '#c4001a', '95-100th percentile']
        ],
        'wet': [
            ['color', '', '#d6d6d6', 'Not Exposed'],
            ['color', '', '#ff8f50', 'Indirectly Exposed'],
            ['color', '', '#ff3b54', 'Directly Exposed']
        ],
        'bp': [
            ['color', '', '#fff0cf', 'Very Low (0 to 1-in-4,643)'],
            ['color', '', '#fdca94', 'Low (1-in-4,643 to 1-in-2,154)'],
            ['color', '', '#fdb27b', 'Low (1-in-2,154 to 1-in-1,000)'],
            ['color', '', '#fc8d59', 'Moderate (1-in-1,000 to 1-in-464)'],
            ['color', '', '#f26d4b', 'Moderate (1-in-464 to 1-in-215)'],
            ['color', '', '#e1452f', 'High (1-in-215 to 1-in-100)'],
            ['color', '', '#c91d13', 'High (1-in-100 to 1-in-46)'],
            ['color', '', '#a90000', 'Very High (1-in-46 to 1-in-22)'],
            ['color', '', '#7f0000', 'Very High (1-in-22+)']
        ],
        'whp': [
            ['color', '', '#38a800', 'Very Low'],
            ['color', '', '#d1ff73', 'Low'],
            ['color', '', '#ffff00', 'Moderate'],
            ['color', '', '#ffaa00', 'High'],
            ['color', '', '#ff0000', 'Very High']
        ],
        'drought': [
            ['color', '', '#ffff00', 'Abnormally Dry'],
            ['color', '', '#ffcc99', 'Moderate Drought'],
            ['color', '', '#ff6600', 'Severe Drought'],
            ['color', '', '#ff0000', 'Extreme Drought'],
            ['color', '', '#660000', 'Exceptional Drought']
        ]
    }
};

export const ODF_DISTRICT_NAMES = {
    "EL-1": "South Cascade",
    "SW-2": "Southwest Oregon",
    "MR-1": "North Cascade",
    "QC": "South Cascade",
    "UA-2": "Douglas FPA",
    "DE-1": "Central Oregon",
    "SW-1": "Southwest Oregon",
    "DG-1": "Douglas FPA",
    "SK-1": "Coos FPA",
    "RWSC": "Southwest Oregon",
    "NW-1": "Northwest",
    "CM-2": "North Cascade",
    "WR-1": "Walker Range FPA",
    "BR-1": "North Cascade",
    "NE-2": "Northeast Oregon",
    "MH-4": "Central Oregon",
    "NE-4": "Northeast Oregon",
    "SW-3": "Southwest Oregon",
    "SL-2": "Western Lane",
    "MA-1": "Central Oregon",
    "CM-1": "North Cascade",
    "KF-1": "Klamath-Lake",
    "WO-3": "West Oregon",
    "NE-3": "Northeast Oregon",
    "RR-2": "Southwest Oregon",
    "UA-3": "South Cascade",
    "WC-2": "Central Oregon",
    "WC-1": "Central Oregon",
    "WL-1": "South Cascade",
    "UA-1": "Douglas FPA",
    "NE-1": "Northeast Oregon",
    "SK-3": "Southwest Oregon",
    "MH-3": "North Cascade",
    "WO-2": "West Oregon",
    "WL-3": "South Cascade",
    "LN-1": "South Cascade",
    "KR": "Klamath-Lake",
    "CS-5": "Coos FPA",
    "NW-3": "Northwest",
    "WW-2": "Northeast Oregon",
    "MH-1": "Central Oregon",
    "DG-2": "Douglas FPA",
    "HLD": "North Cascade",
    "WN-1": "Klamath-Lake",
    "WT-1": "Western Lane",
    "WO-1": "West Oregon",
    "MA-2": "Central Oregon",
    "KF-2": "Klamath-Lake",
    "SW-4": "Southwest Oregon",
    "CS-1": "Coos FPA",
    "MH-2": "North Cascade",
    "CR-1": "Central Oregon",
    "UM-1": "Northeast Oregon",
    "RR-1": "Southwest Oregon",
    "OC-2": "Central Oregon",
    "EC-1": "Central Oregon",
    "WL-2": "South Cascade",
    "RR-3": "Southwest Oregon",
    "HC-1": "Northeast Oregon",
    "EC-2": "Central Oregon",
    "CS-2": "Coos FPA",
    "NW-2": "Northwest",
    "SK-2": "Coos FPA",
    "CS-4": "Coos FPA"
};

export const wwaColors = [
    'case',
    ['==', ['get', 'Event'], '911 Telephone Outage'], '#bfbfbf',
    ['==', ['get', 'Event'], 'Administrative Message'], '#fefefe',
    ['==', ['get', 'Event'], 'Air Quality Alert'], '#7f7f7f',
    ['==', ['get', 'Event'], 'Air Stagnation Advisory'], '#7f7f7f',
    ['==', ['get', 'Event'], 'Arroyo and Small Stream Flood Advisory'], '#00fe7e',
    ['==', ['get', 'Event'], 'Ashfall Advisory'], '#686868',
    ['==', ['get', 'Event'], 'Ashfall Warning'], '#a8a8a8',
    ['==', ['get', 'Event'], 'Avalanche Advisory'], '#cc843e',
    ['==', ['get', 'Event'], 'Avalanche Warning'], '#1d8ffe',
    ['==', ['get', 'Event'], 'Avalanche Watch'], '#f3a35f',
    ['==', ['get', 'Event'], 'Beach Hazards Statement'], '#3fdfcf',
    ['==', ['get', 'Event'], 'Blizzard Warning'], '#fe4400',
    ['==', ['get', 'Event'], 'Blizzard Watch'], '#acfe2e',
    ['==', ['get', 'Event'], 'Blowing Dust Advisory'], '#bcb66a',
    ['==', ['get', 'Event'], 'Brisk Wind Advisory'], '#d7bed7',
    ['==', ['get', 'Event'], 'Child Abduction Emergency'], '#fed600',
    ['==', ['get', 'Event'], 'Civil Danger Warning'], '#feb5c0',
    ['==', ['get', 'Event'], 'Civil Emergency Message'], '#feb5c0',
    ['==', ['get', 'Event'], 'Coastal Flood Advisory'], '#7bfb00',
    ['==', ['get', 'Event'], 'Coastal Flood Statement'], '#6a8d22',
    ['==', ['get', 'Event'], 'Coastal Flood Warning'], '#218a21',
    ['==', ['get', 'Event'], 'Coastal Flood Watch'], '#65cca9',
    ['==', ['get', 'Event'], 'Dense Fog Advisory'], '#6f7f8f',
    ['==', ['get', 'Event'], 'Dense Smoke Advisory'], '#efe58b',
    ['==', ['get', 'Event'], 'Dust Storm Warning'], '#fee3c3',
    ['==', ['get', 'Event'], 'Earthquake Warning'], '#8a4412',
    ['==', ['get', 'Event'], 'Evacuation - Immediate'], '#7efe00',
    ['==', ['get', 'Event'], 'Excessive Heat Warning'], '#c61484',
    ['==', ['get', 'Event'], 'Excessive Heat Watch'], '#7f0000',
    ['==', ['get', 'Event'], 'Extreme Cold Warning'], '#0000fe',
    ['==', ['get', 'Event'], 'Extreme Cold Watch'], '#0000fe',
    ['==', ['get', 'Event'], 'Extreme Fire Danger'], '#e89579',
    ['==', ['get', 'Event'], 'Extreme Wind Warning'], '#fe8b00',
    ['==', ['get', 'Event'], 'Fire Warning'], '#9f512c',
    ['==', ['get', 'Event'], 'Fire Weather Watch'], '#feddac',
    ['==', ['get', 'Event'], 'Flash Flood Statement'], '#8a0000',
    ['==', ['get', 'Event'], 'Flash Flood Warning'], '#8a0000',
    ['==', ['get', 'Event'], 'Flash Flood Watch'], '#2d8a56',
    ['==', ['get', 'Event'], 'Flood Advisory'], '#00fe7e',
    ['==', ['get', 'Event'], 'Flood Statement'], '#00fe00',
    ['==', ['get', 'Event'], 'Flood Warning'], '#00fe00',
    ['==', ['get', 'Event'], 'Flood Watch'], '#2d8a56',
    ['==', ['get', 'Event'], 'Freeze Warning'], '#473c8a',
    ['==', ['get', 'Event'], 'Freeze Watch'], '#00fefe',
    ['==', ['get', 'Event'], 'Freezing Fog Advisory'], '#007f7f',
    ['==', ['get', 'Event'], 'Freezing Rain Advisory'], '#d96fd5',
    ['==', ['get', 'Event'], 'Freezing Spray Advisory'], '#00befe',
    ['==', ['get', 'Event'], 'Frost Advisory'], '#6394ec',
    ['==', ['get', 'Event'], 'Gale Warning'], '#dc9fdc',
    ['==', ['get', 'Event'], 'Gale Watch'], '#febfca',
    ['==', ['get', 'Event'], 'Hard Freeze Warning'], '#9300d2',
    ['==', ['get', 'Event'], 'Hard Freeze Watch'], '#4068e0',
    ['==', ['get', 'Event'], 'Hazardous Materials Warning'], '#4a0081',
    ['==', ['get', 'Event'], 'Hazardous Seas Warning'], '#d7bed7',
    ['==', ['get', 'Event'], 'Hazardous Seas Watch'], '#473c8a',
    ['==', ['get', 'Event'], 'Hazardous Weather Outlook'], '#ede7a9',
    ['==', ['get', 'Event'], 'Heat Advisory'], '#fe7e4f',
    ['==', ['get', 'Event'], 'Heavy Freezing Spray Warning'], '#00befe',
    ['==', ['get', 'Event'], 'Heavy Freezing Spray Watch'], '#bb8e8e',
    ['==', ['get', 'Event'], 'High Surf Advisory'], '#b954d2',
    ['==', ['get', 'Event'], 'High Surf Warning'], '#218a21',
    ['==', ['get', 'Event'], 'High Wind Warning'], '#d9a41f',
    ['==', ['get', 'Event'], 'High Wind Watch'], '#b7850a',
    ['==', ['get', 'Event'], 'Hurricane Force Wind Warning'], '#cc5b5b',
    ['==', ['get', 'Event'], 'Hurricane Force Wind Watch'], '#9831cb',
    ['==', ['get', 'Event'], 'Hurricane Local Statement'], '#fee3b4',
    ['==', ['get', 'Event'], 'Hurricane Warning'], '#db133b',
    ['==', ['get', 'Event'], 'Hurricane Watch'], '#fe00fe',
    ['==', ['get', 'Event'], 'Hydrologic Advisory'], '#00fe7e',
    ['==', ['get', 'Event'], 'Hydrologic Outlook'], '#8fed8f',
    ['==', ['get', 'Event'], 'Ice Storm Warning'], '#8a008a',
    ['==', ['get', 'Event'], 'Lake Effect Snow Advisory'], '#47d0cb',
    ['==', ['get', 'Event'], 'Lake Effect Snow Warning'], '#008a8a',
    ['==', ['get', 'Event'], 'Lake Effect Snow Watch'], '#86cdf9',
    ['==', ['get', 'Event'], 'Lake Wind Advisory'], '#d1b38b',
    ['==', ['get', 'Event'], 'Lakeshore Flood Advisory'], '#7bfb00',
    ['==', ['get', 'Event'], 'Lakeshore Flood Statement'], '#6a8d22',
    ['==', ['get', 'Event'], 'Lakeshore Flood Warning'], '#218a21',
    ['==', ['get', 'Event'], 'Lakeshore Flood Watch'], '#65cca9',
    ['==', ['get', 'Event'], 'Law Enforcement Warning'], '#bfbfbf',
    ['==', ['get', 'Event'], 'Local Area Emergency'], '#bfbfbf',
    ['==', ['get', 'Event'], 'Low Water Advisory'], '#a42929',
    ['==', ['get', 'Event'], 'Marine Weather Statement'], '#feeed4',
    ['==', ['get', 'Event'], 'Nuclear Power Plant Warning'], '#4a0081',
    ['==', ['get', 'Event'], 'Radiological Hazard Warning'], '#4a0081',
    ['==', ['get', 'Event'], 'Red Flag Warning'], '#fe1392',
    ['==', ['get', 'Event'], 'Rip Current Statement'], '#3fdfcf',
    ['==', ['get', 'Event'], 'Severe Thunderstorm Warning'], '#fea400',
    ['==', ['get', 'Event'], 'Severe Thunderstorm Watch'], '#da6f92',
    ['==', ['get', 'Event'], 'Severe Weather Statement'], '#00fefe',
    ['==', ['get', 'Event'], 'Shelter In Place Warning'], '#f97f71',
    ['==', ['get', 'Event'], 'Short Term Forecast'], '#97fa97',
    ['==', ['get', 'Event'], 'Small Craft Advisory'], '#d7bed7',
    ['==', ['get', 'Event'], 'Small Craft Advisory For Hazardous Seas'], '#d7bed7',
    ['==', ['get', 'Event'], 'Small Craft Advisory For Rough Bar'], '#d7bed7',
    ['==', ['get', 'Event'], 'Small Craft Advisory For Winds'], '#d7bed7',
    ['==', ['get', 'Event'], 'Small Stream Flood Advisory'], '#00fe7e',
    ['==', ['get', 'Event'], 'Special Marine Warning'], '#fea400',
    ['==', ['get', 'Event'], 'Special Weather Statement'], '#fee3b4',
    ['==', ['get', 'Event'], 'Storm Warning'], '#9300d2',
    ['==', ['get', 'Event'], 'Storm Watch'], '#fee3b4',
    ['==', ['get', 'Event'], 'Test'], '#effefe',
    ['==', ['get', 'Event'], 'Tornado Warning'], '#fe0000',
    ['==', ['get', 'Event'], 'Tornado Watch'], '#fefe00',
    ['==', ['get', 'Event'], 'Tropical Depression Local Statement'], '#fee3b4',
    ['==', ['get', 'Event'], 'Tropical Storm Local Statement'], '#fee3b4',
    ['==', ['get', 'Event'], 'Tropical Storm Warning'], '#b12121',
    ['==', ['get', 'Event'], 'Tropical Storm Watch'], '#ef7f7f',
    ['==', ['get', 'Event'], 'Tsunami Advisory'], '#d1681d',
    ['==', ['get', 'Event'], 'Tsunami Warning'], '#fc6246',
    ['==', ['get', 'Event'], 'Tsunami Watch'], '#fe00fe',
    ['==', ['get', 'Event'], 'Typhoon Local Statement'], '#fee3b4',
    ['==', ['get', 'Event'], 'Typhoon Warning'], '#db133b',
    ['==', ['get', 'Event'], 'Typhoon Watch'], '#fe00fe',
    ['==', ['get', 'Event'], 'Urban and Small Stream Flood Advisory'], '#00fe7e',
    ['==', ['get', 'Event'], 'Volcano Warning'], '#2e4e4e',
    ['==', ['get', 'Event'], 'Wind Advisory'], '#d1b38b',
    ['==', ['get', 'Event'], 'Wind Chill Advisory'], '#aeeded',
    ['==', ['get', 'Event'], 'Wind Chill Warning'], '#afc3dd',
    ['==', ['get', 'Event'], 'Wind Chill Watch'], '#5e9d9f',
    ['==', ['get', 'Event'], 'Winter Storm Warning'], '#fe68b3',
    ['==', ['get', 'Event'], 'Winter Storm Watch'], '#4581b3',
    ['==', ['get', 'Event'], 'Winter Weather Advisory'], '#7a67ed',
    '#eee'
];